version: '3'
services:
  node:
    build: .
    ports:
    - "3000:3000"
    links:
    - psql
    volumes:
    - ./node:/node
    command: >
      bash -c " cd /node \
        && ls \
        && npm install \
        && nodemon app.js"
  psql:
    image: postgres:10
    ports:
    - "5432:5432"
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_USER=admin