version: '3'
services:
  node:
    build: .
    restart: always
    ports:
    - "3000:3000"
    volumes:
    - ./node:/node
    command: >
      bash -c " cd /node \
        && ls \
        && npm install \
        && nodemon app.js"
  psql:
    image: postgres:10
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    links:
    - node
    environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_USER=admin
    command: >
      bash -c " cd /docker-entrypoint-initdb.d \
        && ls"